USE [ETLDB];

CREATE TABLE [dbo].[CleanNutrition](
	[YearStart] [smallint] NULL,
	[YearEnd] [smallint] NULL,
	[LocationAbbr] [nvarchar](50) NULL,
	[LocationDesc] [nvarchar](50) NULL,
	[Datasource] [nvarchar](50) NULL,
	[Class] [nvarchar](50) NULL,
	[Topic] [nvarchar](50) NULL,
	[Question] [nvarchar](250) NULL,
	[Data_Value_Unit] [nvarchar](1) NULL,
	[Data_Value_Type] [nvarchar](50) NULL,
	[Data_Value] [float] NULL,
	[Data_Value_Alt] [float] NULL,
	[Data_Value_Footnote_Symbol] [nvarchar](50) NULL,
	[Data_Value_Footnote] [nvarchar](100) NULL,
	[Low_Confidence_Limit] [float] NULL,
	[High_Confidence_Limit] [float] NULL,
	[Sample_Size] [int] NULL,
	[Total] [nvarchar](50) NULL,
	[Age_years] [nvarchar](50) NULL,
	[Education] [nvarchar](50) NULL,
	[Gender] [nvarchar](50) NULL,
	[Income] [nvarchar](50) NULL,
	[Race_Ethnicity] [nvarchar](50) NULL,
	[GeoLocation] [nvarchar](50) NULL,
	[ClassID] [nvarchar](50) NULL,
	[TopicID] [nvarchar](50) NULL,
	[QuestionID] [money] NULL,
	[DataValueTypeID] [nvarchar](50) NULL,
	[LocationID] [tinyint] NULL,
	[StratificationCategory1] [nvarchar](50) NULL,
	[Stratification1] [nvarchar](50) NULL,
	[StratificationCategoryId1] [nvarchar](50) NULL,
	[StratificationID1] [nvarchar](50) NULL
)